# Generated by Django 5.1.4 on 2024-12-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inventory_images/'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
